apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
  labels: 
    group: maestro
spec:
  storageClassName: rook-cephfs-east
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 60Gi