apiVersion: batch/v1
kind: Job
metadata:
  name: test-schuduler
  labels:
    group: maestro
spec:
  template:
    metadata:
      name: test-schuduler
      labels:
        k8s-app: test-schuduler
    spec:
      serviceAccountName: maestro
      containers:
      - name: schuduler
        image: ghcr.io/ucsd-e4e/maestro_scheduler:main
        imagePullPolicy: Always 
        env:
          - name: TRAINER_IMAGE
            value: ghcr.io/ucsd-e4e/maestro_trainer:main
          - name: SERVER_URL
            value: https://test-service2.nrp-nautilus.io
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        volumeMounts:
          - name: data-pvc
            mountPath: /data/
        resources:
          limits:
            memory: 12Gi
            cpu: "1"
          requests:
            memory: 10Gi
            cpu: "1"
      restartPolicy: Never
      imagePullSecrets:
        - name: regcred
      volumes:
      - name: data-pvc
        persistentVolumeClaim:
          claimName: data-pvc